a = input('Digite algo: ')
print('O tipo primitivo desse valor é ',type(a))
print('Só tem espaços? ', a.isspace())
print('é um número?', a.isnumeric())
print('é alfabético?', a.isalpha())
print('é alfanumérico',a.isalpha())
